### PR TITLE
Fix attribute key sorting issue

### PR DESCRIPTION
**Pull request by ccmEnlil**
Was getting errors trying to sort by page attributes.  Andrew's provided fix alleviates the issue... https://github.com/concrete5/concrete5/issues/4916

### CODE REVIEW

**Comment by ccmEnlil** [comment]
I left the code as is, unsure of what direction it may need to take.  Not sure of the backward compatibility this new PL+ repository has taken on, or exactly what 5.7 - 8 version that code changed in the c5 core...

**Comment by ccmEnlil** [comment]
looking at c5 version dates etc, we should be good backwards to 8.3.x, just replacing the two lines...

**Comment by skybluesofa** [comment]
@c5enlil Thanks for your work on this.

**Comment by ccmEnlil** [comment]
@skybluesofa, Powerful piece of work here.  Happy to help keep it alive!!

**Pull request merged**
